name: VerifyPR
on:
  pull_request_target:
    types: [opened, edited]

jobs:
  checkTargetBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          change-to: develop
          exclude: RayWangQvQ/BiliBiliToolPro:develop
          comment: |
              Your PR was set to `main`, but PRs should be sent to `develop`
              The base branch of this PR has been automatically changed to `develop`, please check that there are no merge conflicts.
